name: Deploy Container

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: sandialabs
          password: ${{ secrets.CR_PAT }}

      - name: Set image tags
        id: image-tags
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "tags=ghcr.io/sandialabs/bibcheck-wasm:${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          else
            echo "tags=ghcr.io/sandialabs/bibcheck-wasm:latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push container
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image-tags.outputs.tags }}
